export const DoctorsColumsDetails = [
  {
    Id: 1,
    SlNo: 1,
    Picture: "Aegon NV",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0943654321",
    Phone: "34567324",
    password: "pass@11",
    action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/09/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 2,
    SlNo: 2,
    Picture: "State Street Corporation",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "09434654321",
    Phone: "4365345634",
    password: "pass@11",
    Action: "Active",
    sex: "Female",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 3,
    SlNo: 3,
    Picture: "Urban Outfitters, Inc.",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/06/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 4,
    SlNo: 4,
    Picture: "Airgain, Inc.",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 5,
    SlNo: 5,
    Picture: "Big Lots, Inc.",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 6,
    SlNo: 6,
    Picture: "American Campus Communities Inc",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 7,
    SlNo: 7,
    Picture: "Quest Resource Holding Corporation.",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 8,
    SlNo: 8,
    Picture: "SunTrust Banks, Inc.",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 9,
    SlNo: 9,
    Picture: "Northwest Natural Gas Company",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
  {
    Id: 10,
    SlNo: 10,
    Picture: "The Kraft Heinz Company",
    FirstName: "fhjaj kka",
    LastName: "LastName",
    department: "sd kd",
    designation: "web deveplore",
    email: "email",
    mobile: "0987654321",
    Phone: "1234567890",
    password: "pass@11",
    Action: "Active",
    sex: "Male",
    address: "Jaipur",
    BloodGroup: "BloodGroup",
    dob: "01/04/1993",
    role: "role",
    CreateDate: "CreateDate",
    Status: "Status",
    specialist: "Specialist",
  },
];
